import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  ClipboardCheck,
  CreditCard,
  Download,
  FileCheck,
  FileText,
  Filter,
  FlaskConical,
  Home,
  IdCard,
  Inbox,
  LayoutDashboard,
  LockKeyhole,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Package,
  PackageCheck,
  PackageOpen,
  Pill,
  Phone,
  Plus,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Store,
  Truck,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

export const icons = {
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  boxes: Boxes,
  calendar: Calendar,
  check: Check,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  circle: Circle,
  clock: Clock,
  "clipboard-check": ClipboardCheck,
  "credit-card": CreditCard,
  download: Download,
  "file-check": FileCheck,
  "file-text": FileText,
  filter: Filter,
  flask: FlaskConical,
  home: Home,
  "id-card": IdCard,
  inbox: Inbox,
  "layout-dashboard": LayoutDashboard,
  lock: LockKeyhole,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  package: Package,
  "package-check": PackageCheck,
  "package-open": PackageOpen,
  pill: Pill,
  phone: Phone,
  plus: Plus,
  search: Search,
  send: Send,
  settings: Settings,
  "shield-check": ShieldCheck,
  sliders: SlidersHorizontal,
  store: Store,
  truck: Truck,
  upload: Upload,
  user: User,
  "user-plus": UserPlus,
  users: Users,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

type IconProps = LucideProps & {
  name: IconName;
};

export function Icon({ name, strokeWidth = 1.8, ...props }: IconProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" focusable="false" strokeWidth={strokeWidth} {...props} />;
}
